### PR TITLE
Now able to add extra properties to message object

### PR DESCRIPTION
**Pull request by rogeriocsilva**
So i can have additional properties to click events

### CODE REVIEW

**Comment by kreuzerk** [comment]
@rogeriocsilva Thanks a lot for the PR. Sorry that I did not respond yet. Last week I was on holidays and  I just returned. I will look at the PR in the next couple of days.

**Comment by rogeriocsilva** [comment]
No problem man, i think this is useful yet i don't think extra is a good keyword, feel free to give it a more relevant keyword.

**Comment by kreuzerk** [comment]
Muito obrigado @rogeriocsilva. Great work!!
If you still have more ideas just continue to create PR's!

**Comment by rogeriocsilva** [comment]
np man, i'm trying to do a pause on hover but i'm still not comfortable with rxjs :\

**Comment by kreuzerk** [comment]
This would be a great feature. To achieve this I think we need to delay the life time stream of the message. To discuss further I have created an issue https://github.com/kreuzerk/primeNG-advanced-growl/issues for this feature.

**Pull request merged**
